version: "3.9"

services:
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: simple_board
      TZ: Asia/Seoul
    volumes:
      - ./data:/var/lib/mysql
    container_name: local-mysql
    ports:
      - 3316:3306
